name: Merge branches

on:
  push:
    branches:
      - poc

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge branches
      run: |
        git config user.name "Your GitHub Username"
        git config user.email "your.email@example.com"

        git merge --no-ff main -m "Merge 'main' into 'poc'"
        git push

    - name: Print Merge Commit Details
      run: |
        git log -1


