name: GCP Access Request Workflow

on:
  push:
    branches:
      - main

jobs:
  access_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run access request script
        run: python handle_request.py
        - name: List files in the current directory
  run: ls

